# Add config stuff for my fork, see https://www.gitpod.io/docs/checkout-location
# Possibly rename to gotty for compartibility, probably.
#checkoutLocation: "go/src/github.com/MadeByThePinsHub/yudai-gotty"
#workspaceLocation: "go/src/github.com/MadeByThePinsHub/yudai-gotty"

# Use default image
image:
  image: .gitpod.Dockerfile

# tasks
tasks:
  - name: devbuild
    command: |
      go get -v ./...
      make tools && make

# Extensions
vscode:
  extensions:
    - golang.go