---
# Use default image
image:
  file: .gitpod.Dockerfile
  context: .

# tasks
tasks:
  - name: devbuild
    init: |
      go get -v ./...
      make tools 
    command: |
      make && gp sync-done gitpod-binary-build
  - name: Test built binary
    before: docker pull ghcr.io/code-server-boilerplates/starter-pack:develop
    command: |
      gp sync-await gitpod-binary-build
      $PWD/gotty -w --reconnect docker run -it --rm --workdir /workspace -v /workspace/.gotty-devel/csb-starter-pack:/workspace ghcr.io/code-server-boilerplates/starter-pack:develop shell

# Extensions
vscode:
  extensions:
    - golang.go
    - eamodio.gitlens
    - vscode-icons-team.vscode-icons
    - ms-vscode.makefile-tools
