# Add config stuff for my fork, see https://www.gitpod.io/docs/checkout-location
checkoutLocation: "go/src/github.com/ajhalili2006/gotty"
workspaceLocation: "go/src/github.com/ajhalili2006/gotty"

# Use default image
image:
  image: .gitpod.Dockerfile

# tasks
tasks:
  - name: devbuild
    command: |
      go get -v ./...
      make all

# Extensions
vscode:
  extensions:
    - golang.go