name: Build and upload to JFrog Artifactory

on:
  push:

jobs:
  build-binary:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      # Setup Golang env first
      - name: Setup Go environment
        uses: actions/setup-go@v2.1.3
      # Then upgrade to Node.js 16.x
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.2.0
        with:
          # Node.js 16.x is still not an LTS as of time of commiting this file
          # But we should test it BTW.
          node-version: 16.x

      - name: Upgrade npmjs
        run: sudonpm i -g npm

      - name: Install build tools
        run: |
          env | grep GOPATH
          make install-tools

      - name: Build Golang binary
        run: make

      - name: Test built binary
        run: ./gotty -v

      # TODO: Add stuff for collecting build artifacts here
