name: Cross-platform Complier CI

on:
  - push

jobs:
  build:
    name: Run cross-complier
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Test
      run: make test

    - name: Build
      run: make tools cross_compile
    
          # TODO: Add stuff for collecting build artifacts here
    - name: Upload built binaries
      uses: actions/upload-artifact@v2.2.4
      with:
        # Artifact name
        name: gotty-build-ci
        # A file, directory or wildcard pattern that describes what to upload
        path: ./builds/pkg
        retention-days: 14
