---
name: Generate an pre-release

on:
  push:
    branches:
      - "main"


jobs:
  pre-release:
    name: "Pre Release"
    runs-on: "ubuntu-latest"

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16


    - name: "Build & test"
      run: "make tools release-artifacts"

    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GH_SERVICE_ACCOUNT_API_KEY }}"
        automatic_release_tag: develop
        prerelease: true
        title: "golang-builds:develop"
        files: |
          LICENSE
          builds/dist/*